### users.getAll
GET http://localhost:8080/users
X-Login: vasya
X-Password: password

### users.getById
GET http://localhost:8080/users/1
X-Login: vasya
X-Password: password

### users.create
POST http://localhost:8080/users
X-Login: vasya
X-Password: password
Content-Type: application/json

{
  "id": 0,
  "login": "vanya",
  "password": "secret",
  "roles": ["ROLE_ADMIN"]
}

### users.update
PUT http://localhost:8080/users
X-Login: vasya
X-Password: password
Content-Type: application/json

{
  "id": 3,
  "login": "vanya",
  "password": "secret"
}

### users.deleteById
DELETE http://localhost:8080/users/3
X-Login: vasya
X-Password: password



### posts.getAll
GET http://localhost:8080/posts
X-Login: vasya
X-Password: password

### posts.getById
GET http://localhost:8080/posts/2
X-Login: vasya
X-Password: password

### posts.create
POST http://localhost:8080/posts
X-Login: vasya
X-Password: password
Content-Type: application/json

{
  "id": 0,
  "name": "privet",
  "content": "Hello world!",
  "tags": ["#HELLO", "WORLD"],
  "geo": {
    "lat": 50.00,
    "lng": 40.00
  }
}

### posts.update
PUT http://localhost:8080/posts
X-Login: vasya
X-Password: password
Content-Type: application/json

{
  "id": 2,
  "name": "new1",
  "content": "new update",
  "tags": ["NEW"],
  "geo": {
    "lat": 70.50,
    "lng": 30.40
  }
}

### posts.deleteById
DELETE http://localhost:8080/posts/3
X-Login: vasya
X-Password: password
