### users.getAll
GET http://localhost:8080/users
X-Login: vasya
X-Password: password

### users.getById
GET http://localhost:8080/users/1111
X-Login: vasya
X-Password: password

### users.create
POST http://localhost:8080/users
X-Login: vasya
X-Password: password
Content-Type: application/json

{
  "id": 0,
  "login": "vanya",
  "password": "secret",
  "roles": ["ROLE_CLIENT"]
}

### users.update
PUT http://localhost:8080/users
X-Login: vasya
X-Password: password
Content-Type: application/json

{
  "id": 3,
  "login": "vanya",
  "password": "secret",
  "roles": ["ROLE_CLIENT"]
}

### users.deleteById
DELETE http://localhost:8080/users/3
X-Login: vasya
X-Password: password

### posts.getAll
GET http://localhost:8080/posts
X-Login: vasya
X-Password: password

### posts.getById
GET http://localhost:8080/posts/222
X-Login: vasya
X-Password: password

### posts.create
POST http://localhost:8080/posts
X-Login: vasya
X-Password: password
Content-Type: application/json

{
  "id": 0,
  "name": "hello",
  "content": "Hello world!",
  "tags": ["#HELLO", "#Ёшка"],
  "geo": {
    "lat": 10.00,
    "lng": 20.00
  }
}

### posts.update
PUT http://localhost:8080/posts
X-Login: vasya
X-Password: password
Content-Type: application/json

{
  "id": 1,
  "name": "new1",
  "content": "new update",
  "tags": ["NEW"],
  "geo": {
    "lat": 70.50,
    "lng": 30.40
  }
}

### posts.deleteById
DELETE http://localhost:8080/posts/3
X-Login: vasya
X-Password: password
